// Vercel serverless function — adapts TanStack Start's Web Fetch handler
// to Vercel's Node.js IncomingMessage/ServerResponse interface.
// Built at deploy time: dist/server/server.js is generated by `npm run build`.

export const config = { runtime: "nodejs" };

export default async function handler(req, res) {
  // Dynamically import after build
  const { createServerEntry } = await import("../dist/server/server.js");
  const app = createServerEntry();

  // Build full URL
  const protocol = req.headers["x-forwarded-proto"] || "https";
  const host = req.headers["x-forwarded-host"] || req.headers.host;
  const url = `${protocol}://${host}${req.url}`;

  // Convert Node headers → Web Headers
  const headers = new Headers();
  for (const [key, val] of Object.entries(req.headers)) {
    if (val != null) {
      headers.set(key, Array.isArray(val) ? val.join(", ") : val);
    }
  }

  // Read body for non-GET requests
  let body = undefined;
  if (req.method !== "GET" && req.method !== "HEAD") {
    body = await new Promise((resolve, reject) => {
      const chunks = [];
      req.on("data", (chunk) => chunks.push(chunk));
      req.on("end", () => resolve(Buffer.concat(chunks)));
      req.on("error", reject);
    });
  }

  // Call the fetch handler
  const webResponse = await app.fetch(
    new Request(url, { method: req.method, headers, body }),
    {},
  );

  // Write response back to Node
  res.statusCode = webResponse.status;
  webResponse.headers.forEach((value, key) => {
    res.setHeader(key, value);
  });
  const buf = await webResponse.arrayBuffer();
  res.end(Buffer.from(buf));
}
